### ISSUE TITLE
Remove the mysterious extra space after ingredients

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Meals-From-Around-The-World#2]
For dishes with less ingredients, there is a lot of extra space visible before the instructions. The amount of this space seems to be inversely proportional to the number of ingredients. Investigate what is causing so many blank lines and fix the UI so that there are no unpredictable blank lines after the list of ingredients.

Hint: Investigate the data being returned by the API

Attach 2 screenshots, one for before and for after, showing how you have fixed this UI bug. Feel free to elaborate in writing how you figured out what exactly was wrong, since finding the root cause of a bug is as important as fixing it.

Visual changes are much easier for PR reviewers when the contributor adds screenshots / gifs, as appropriate, which show the change at a cursory glance, so make this a habit!

**Comment by ghost** [comment]
Can I work on this Issue?
Before:
<img width="1120" alt="1" src="https://user-images.githubusercontent.com/96474794/157810178-ceb729b4-5869-4263-9886-2dd86197606d.png">

After: 
<img width="1120" alt="1" src="https://user-images.githubusercontent.com/96474794/157809836-3a7171da-98c1-4d88-96a0-832a5c550e9a.png">

**Comment by N-Shar-ma** [comment]
@delClg Sure, awaiting your PR!

**Comment by KarthikS373** [comment]
Ma'am can u assign this to me?

**Comment by superiorsd10** [comment]
@N-Shar-ma Ma'am, I think I acquire enough knowledge to resolve this issue. So please consider assigning it to me.

**Comment by N-Shar-ma** [comment]
@superiorsd10 Go ahead, you have 3 hours

**Comment by KarthikS373** [comment]
Ma'am can I get this one assigned
